version: '2'
services:
  web:
    container_name: tad-app
    build: 
      context: .
      dockerfile: ./docker/flask/Dockerfile
    volumes:
      - ./src:/app
    depends_on:
      - redis
    networks:
      - tadnet
  nginx:
    container_name: tad-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tadnet
  redis:
    container_name: tad-redis
    image: redis:latest
    networks:
      - tadnet
networks:
  tadnet:
    driver: bridge
